version: '3.5'

services:
  server:
    build: server
    image: chatty/server
    privileged: true
    networks:
      - vnet

networks:
  vnet:
    driver: bridge
    ipam:
      config:
        - subnet: 172.16.230.0/24
